channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=25.0.1
- pip:
  - mlflow==2.20.2
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==6.1.0
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
